ARG TAG_NAME="latest"
FROM awiciroh/datastream-deps:${TAG_NAME} AS datastream_base
# Copy files directly from the parent context
COPY . /datastreamcli/
COPY configs/ /ngen-datastreamcli/configs/
RUN pip3 install -e datastreamcli/ && \
    groupadd -r mygroup && \
    useradd -r -g mygroup myuser
COPY --chown=myuser:mygroup . /datastreamcli
