ARG TAG_NAME="latest"
FROM awiciroh/datastream-deps:${TAG_NAME} AS datastream_base
COPY . /datastreamcli/
RUN ln -sf /usr/bin/python3.11 /usr/bin/python3 && \
    uv pip install --system --python python3.11 -e /datastreamcli && \
    uv pip install --system --python python3.11 pytest && \
    groupadd -r mygroup && useradd -r -g mygroup myuser && \
    chown -R myuser:mygroup /datastreamcli
