name: Datastream x datastream Integration on X86
on:
  workflow_dispatch:
    inputs:
      ds_tag:
        description: 'DS Docker version tag which you want to test with'
        required: false
        default: ''
        type: string
      fp_tag:
        description: 'FP Docker version tag which you want to test with'
        required: false
        default: ''
        type: string
  push:
    branches:
      - main
    paths:
      - 'docker/**' 
      - 'src/datastreamcli/**'
      - 'tests/**'
      - '!src/datastreamcli/README.md'
  pull_request:
    paths:
      - 'docker/**' 
      - 'src/datastreamcli/**'
      - 'tests/**'
      - '!src/datastreamcli/README.md'
  
permissions:
  contents: read
  security-events: write 

jobs:
  build-test-docker-x86:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}        

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1
        
    - name: Build docker containers
      run : |        
        if [ -z "${{ inputs.fp_tag }}" ]; then
          echo "FP_TAG input not provided, building datastream containers..."
          TAG=test-x86 docker compose -f docker/docker-compose.yml build datastream-deps
          TAG=test-x86 docker compose -f docker/docker-compose.yml build datastream
        else
          echo "FP_TAG input provided (${{ inputs.fp_tag }}), skipping datastream build and using existing images..."
        fi

    - name: Test docker containers
      env:
        DS_TAG: ${{ inputs.ds_tag || 'test-x86' }}
        FP_TAG: ${{ inputs.fp_tag || 'test-x86' }}
      run : |
        docker images
        curl -L -O https://ngen-datastream.s3.us-east-2.amazonaws.com/palisade.gpkg
        ./scripts/datastream -s 202006200100 -e 202006200200 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g $(pwd)/palisade.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
