# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Datastream Python Configuration
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'python_tools/**'
      - '!python_tools/README.md'
  pull_request:
    branches:
      - main    
    paths:      
      - 'python_tools/**'
      - '!python_tools/README.md'
      
permissions:
  contents: read
jobs:
  test-python-configuration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest

    - name: Test with pytest
      run: |
        python -m pytest tests/test_configuration.py
